sudo: required # We need to super user permissions to execute our build
services:
  - docker # It will install docker 

before_install: # These will install before our tests/deployment is/are run
  - docker build -t habeeb223/docker-react -f Dockerfile.dev .

script: # All commands to execute the test or deployment
  - docker run -e CI=true habeeb223/docker-react npm run test
